language: go

go:
  - "1.15"

before_install:
  - go get -t -v ./...
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

script:
  - make lint
  # - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)